services:
  # Job ETL batch (analyse des températures)
  etl:
    build: .
    container_name: spark-etl
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - "4040:4040"
    command: python src/main.py
    stdin_open: true
    tty: true

  # API de requêtage
  api:
    build: .
    container_name: spark-api
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - "8000:8000"
      - "4041:4040"
    command: python src/api/main.py
